# Generated by Django 2.1 on 2018-08-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app00', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='user_detail',
        ),
    ]
